# .travis.yml for Scala projects


language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

scala:
   - 2.11.7

jdk:
  - openjdk8
 
script:
   - sbt ++$TRAVIS_SCALA_VERSION test

notifications:
  slack: n2nplace:po7Zzne5pBkVqO5tV8To2KuA
  email:
    on_success: change
    on_failure: change
  
# Use container-based infrastructure
sudo: false
